In [ ]:
import urllib.request
url = ("https://raw.githubusercontent.com/rasbt/"
"LLMs-from-scratch/main/ch02/01_main-chapter-code/"
"the-verdict.txt")
file_path = "the-verdict.txt"
urllib.request.urlretrieve(url, file_path)


('the-verdict.txt', <http.client.HTTPMessage at 0x7f18579cac10>)

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()
print("total Number of characters:", len(raw_text))
print(raw_text[:99]) #print first 100 characters.

total Number of characters: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [ ]:
import re
text = "Hello, world. This is a test"
result = re.split(r'(\s)', text)
print(result)

['Hello,', ' ', 'world.', ' ', 'This', ' ', 'is', ' ', 'a', ' ', 'test']


In [ ]:
import re
text = "Hello, world. This is a test"
result = re.split(r'([,.]|\s)', text)
print(result)
print(len(result))

['Hello', ',', '', ' ', 'world', '.', '', ' ', 'This', ' ', 'is', ' ', 'a', ' ', 'test']
15


In [ ]:
import re
text = "Hello, world. This is a test"
result = re.split(r'([,.]|\s)', text)

result = [item for item in result if item.strip()]
print(result)
print(len(result))


['Hello', ',', 'world', '.', 'This', 'is', 'a', 'test']
8


In [ ]:
import re
text = "Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)

result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [ ]:
import re
# text = "Hello, world. Is this-- a test?"
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)

preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed))

4690


In [ ]:
print(preprocessed[:99])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter']


# Converting tokens into token IDs
build vocabulary first,

In [ ]:
all_words  = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

1130


In [ ]:
# vocab = {token:integer for token,integer in enumerate(all_words)}
vocab = {token: integer for integer, token in enumerate(all_words)}
print("Printing the dictionary: ")
for i, item in enumerate(vocab.items()):
  print (item)
  if i>50:
    break

Printing the dictionary: 
('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)


next goal to apply this vocabulary to convert new text into token IDs.

In [ ]:
class SimpleTokenizerV1:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {i:s for s,i in vocab.items()} #create an inverse vocab that maps token IDs back to original text tokens

  def encode(self, text): # process input text into token IDs
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [item.strip() for item in preprocessed if item.strip()]
    # print(preprocessed)  # debugging
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids

  def decode(self, ids): #converts token ids back into text
    text = " ".join([self.int_to_str[i] for i in ids])
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text) #removes spaces before the specified punctuation
    return text

In [ ]:
tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know,"
Mrs. Gisburn said with pardonable pride."""
# text = "it"

print("tokenizing the text to ids: ")
ids = tokenizer.encode(text)
print(ids)
print("detokenizing the ids to text: ")
# print("tokenizing the text: ")
tokens = tokenizer.decode(ids)
print(tokens)

tokenizing the text to ids: 
[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]
detokenizing the ids to text: 
" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


In [ ]:
tokenizer = SimpleTokenizerV1(vocab)

text = "Hello, Do you like tea?" #Hello not used in the text we provided! No tokens.
# text = "it"

print("tokenizing the text to ids: ")
ids = tokenizer.encode(text)
print(ids)
print("detokenizing the ids to text: ")
# print("tokenizing the text: ")
tokens = tokenizer.decode(ids)
print(tokens)

tokenizing the text to ids: 


KeyError: 'Hello'

# 2.4 Adding Special context tokens

In [ ]:
import re
# text = "Hello, world. Is this-- a test?"
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)

preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed))

all_tokens  = sorted(set(preprocessed))
vocab_size = len(all_tokens)
print(vocab_size)




4690
1130


In [ ]:
all_tokens.extend(["<|endoftext|>", "<|unk|>"])
vocab_size = len(all_tokens)
print(vocab_size)

1132


In [ ]:
vocab = {token:integer for integer, token in enumerate(all_tokens)}
print(len(vocab.items()))

1132


In [ ]:
for i,item in enumerate(list(vocab.items())[-5:]):
  print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
class SimpleTokenizerV2:
  def __init__(self, vocab):
    self.str_to_int = vocab
    self.int_to_str = {i:s for s,i in vocab.items()} #create an inverse vocab that maps token IDs back to original text tokens

  def encode(self, text): # process input text into token IDs
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [item.strip() for item in preprocessed if item.strip()]
    preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed] #to handle unknown
    # print(preprocessed)  # debugging
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids

  def decode(self, ids): #converts token ids back into text
    text = " ".join([self.int_to_str[i] for i in ids])
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text) #removes spaces before the specified punctuation
    return text

In [ ]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit tarraces of the palcace."

text = " <|endoftext|> ".join([text1, text2]) #Add the endoftext token between the two texts.

print(text)

Hello, do you like tea? <|endoftext|> In the sunlit tarraces of the palcace.


In [ ]:
tokenizer = SimpleTokenizerV2(vocab)
print(tokenizer.encode(text))

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 1131, 722, 988, 1131, 7]


In [ ]:
print(tokenizer.decode(tokenizer.encode(text)))


<|unk|>, do you like tea? <|endoftext|> In the sunlit <|unk|> of the <|unk|>.


# Byte Pair Encoding (BPE)

In [ ]:
#efficiently implemented by openai
#use the package tiktoken
!pip install tiktoken

In [ ]:
import tiktoken
tokenizer = tiktoken.get_encoding('gpt2')

In [ ]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit tarraces of"
    " someunknown palcace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 256, 3258, 2114, 286, 617, 34680, 6340, 66, 558, 13]


In [ ]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> In the sunlit tarraces of someunknown palcace.


Exercise 2.1: BPE

In [ ]:
unknown_word = "Akwirw ier"
integers = tokenizer.encode(unknown_word)
print("encoded into token IDs: ", integers)

encoded into token IDs:  [33901, 86, 343, 86, 220, 959]


In [ ]:
tokens = tokenizer.decode(integers)
print("decoding the IDs back to tokens :", tokens)


decoding the IDs back to tokens : Akwirw ier


In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

enc_text = tokenizer.encode(raw_text)

print(len(enc_text))

5145


In [ ]:
enc_sample = enc_text[50:] #remove first 50 tokens from the dataset

# 2.4 Data Sampling with sliding window

In [ ]:
#creating input-target pair

context_size = 4 # how many tokens are included in the input.
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x : {x}")
print(f"y :      {y}")

x : [290, 4920, 2241, 287]
y :      [4920, 2241, 287, 257]


In [ ]:
for i in range(1, context_size+1):
  context = enc_sample[:i]
  desired = enc_sample[i]
  print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


using same method, creating the data loader

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class GPTDatasetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.target_ids = []

    token_ids = tokenizer.encode(txt) #tokenize the entire text

    for i in range(0, len(token_ids) - max_length, stride): # uses a sliding window to chunk the book into overlapping sequences of max_length
      input_chunk = token_ids[i:i + max_length]
      target_chunk = token_ids[i+1: i + max_length + 1]

      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(target_chunk))

  def __len__(self): # returns the total number of rows in the dataset
    return len(self.input_ids)

  def __getitem__(self, idx): # returns the single row from the dataset
    return self.input_ids[idx], self.target_ids[idx]

A data loader to generate batches with input-target pairs

In [ ]:
def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):
  tokenizer = tiktoken.get_encoding('gpt2')
  dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
  dataloader = DataLoader(
      dataset,
      batch_size=batch_size,
      shuffle=shuffle,
      drop_last=drop_last,
      num_workers=num_workers
  )

  return dataloader

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [ ]:
second_batch = next(data_iter) # we used stride = 1
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


Exercise 2.2 : max_length:2, stride:2 & max_length=8, stride=2

In [ ]:
dataloader_ex1 = create_dataloader_v1(raw_text, batch_size=1, max_length=2, stride=2, shuffle=False)

data_iter_ex1 = iter(dataloader_ex1)
first_batch_ex1 = next(data_iter_ex1)
print(first_batch_ex1)

print("Second Batch")
second_batch_ex1 = next(data_iter_ex1) # we used stride = 1
print(second_batch_ex1)

[tensor([[ 40, 367]]), tensor([[ 367, 2885]])]
Second Batch
[tensor([[2885, 1464]]), tensor([[1464, 1807]])]


In [ ]:
dataloader_ex2 = create_dataloader_v1(raw_text, batch_size=1, max_length=8, stride=2, shuffle=False)

data_iter_ex2 = iter(dataloader_ex2)
first_batch_ex2 = next(data_iter_ex2)
print(first_batch_ex2)

print("Second Batch")
second_batch_ex2 = next(data_iter_ex2) # we used stride = 1
print(second_batch_ex2)

[tensor([[  40,  367, 2885, 1464, 1807, 3619,  402,  271]]), tensor([[  367,  2885,  1464,  1807,  3619,   402,   271, 10899]])]
Second Batch
[tensor([[ 2885,  1464,  1807,  3619,   402,   271, 10899,  2138]]), tensor([[ 1464,  1807,  3619,   402,   271, 10899,  2138,   257]])]


changing the batch size now

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

dataloader = create_dataloader_v1(raw_text, batch_size=4, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs: \n", inputs)
print("\n\n\nTargets: \n", targets)

Inputs: 
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257]])



Targets: 
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922]])


# 2.7 Creating Token Embeddings:
converting token IDs to token embeddings
token embeddings: continous values vector

In [ ]:
input_ids = torch.tensor([2,3,5,1])

In [ ]:
vocab_size = 6
output_dims = 3


In [ ]:
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dims)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [ ]:
# Now, apply it to one token to obtain the embedding vector.
print(embedding_layer(torch.tensor([3])))

In [ ]:
print(embedding_layer(input_ids))


tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


# 2.8 Encoding Word Positions

In [ ]:
vocab_size = 50257
output_dims = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dims)

In [ ]:
max_length = 4 # 4 tokens per batch
dataloader = create_dataloader_v1(
    raw_text,
    batch_size = 8,
    max_length=max_length,
    stride=max_length,
    shuffle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print(f"Input IDs:\n{inputs}")
print(f"Input Shape:\n{inputs.shape}")

Input IDs:
tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Input Shape:
torch.Size([8, 4])


In [ ]:
#now, converting these token IDs to embeddings
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)
#Each token id is embedded as 256-dimensional vector

torch.Size([8, 4, 256])


In [ ]:
context_length = max_length
pos_embeddings_layer = torch.nn.Embedding(context_length,output_dims)
pos_embeddings = pos_embeddings_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [ ]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
